### ISSUE TITLE
point_cloud parse error

### ISSUE THREAD

**Issue by AldrichCabrera** [UCSD-E4E/maya-archaeology#1]
Hello!

I have a question about the orb slam reconstruction. I've performed all the steps to launch the algorithm but I found a problem that it says: 

**[pcl::PLYReader] point_cloud/001350.ply:1 parse error
   [pcl::PLYReader::read] problem parsing header!
   [pcl::PLYReader::read] problem parsing header!
   [pcl::PLYWriter::writeASCII] Input point cloud has no data!**

**Comment by qkgautier** [comment]
If I remember correctly, we had some problems with some versions of PCL. PCL 1.8 fixes some issues related to the PLY format.

**Comment by AldrichCabrera** [comment]
Ok, I tried to change my PCL version and compile the package again. Thank you so much!!
